### ISSUE TITLE
Analysis document

### ISSUE THREAD

**Issue by dhakelila** [hotosm/design-strategy#4]
Hi HOT community! 

Clara Linos from Vizzuality here.
As you might know, we are taking care of the new design strategy for HOT. 

We started by analysing your current website (hotosm.org) and your tools to better understand what HOT is about. 
We also talked with some of you and we developed a survey to better understand what HOT means for you and what we'd like to transmit with our new style.

In the attached document you will be able to see our research and our conclusions. 

Please, consider it as a work in progress. And if you have something to share or add please, do. 

[ANALYSIS (1).pdf](https://github.com/hotosm/design-strategy/files/978938/ANALYSIS.1.pdf)

**Comment by smit1678** [comment]
Thanks @dhakelila. See #3 for the input on the hierarchy from the working group. 

@dhakelila Can you list out what's planned next for this or needed for input here? 

Other side note: can we clean up the spellings of OpenStreetMap, HOT, etc?

**Comment by dhakelila** [comment]
Hi @smit1678, 

Sorry for the misspelling. We are addressing it asap. 

I'm opening a new thread with next steps #5 !

**Comment by dhakelila** [comment]
Document updated in my first comment.
